version: '3.8'

services:
  stt-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stt_server
    ports:
      - "5025:5025"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: ["python3", "stt_websocket_server.py"]
